// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRtgTf9Wugn-aJ8dTq18E63JbP7Htuujs',
    appId: '1:32205512588:web:ed23fe95f2f157792e00a9',
    messagingSenderId: '32205512588',
    projectId: 'flash-chat-ea0e6',
    authDomain: 'flash-chat-ea0e6.firebaseapp.com',
    storageBucket: 'flash-chat-ea0e6.appspot.com',
    measurementId: 'G-K9RHV11EDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV9rnEehycqqT48m8BQusLZdlJy31f0LE',
    appId: '1:32205512588:android:a8c857bfced0e6ca2e00a9',
    messagingSenderId: '32205512588',
    projectId: 'flash-chat-ea0e6',
    storageBucket: 'flash-chat-ea0e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfaVr15tuLy5fnBFaAJlxpwW0MNcrW3_0',
    appId: '1:32205512588:ios:4609abecff22d7d02e00a9',
    messagingSenderId: '32205512588',
    projectId: 'flash-chat-ea0e6',
    storageBucket: 'flash-chat-ea0e6.appspot.com',
    iosBundleId: 'com.example.flashChatProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfaVr15tuLy5fnBFaAJlxpwW0MNcrW3_0',
    appId: '1:32205512588:ios:4609abecff22d7d02e00a9',
    messagingSenderId: '32205512588',
    projectId: 'flash-chat-ea0e6',
    storageBucket: 'flash-chat-ea0e6.appspot.com',
    iosBundleId: 'com.example.flashChatProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRtgTf9Wugn-aJ8dTq18E63JbP7Htuujs',
    appId: '1:32205512588:web:df24025e04d142582e00a9',
    messagingSenderId: '32205512588',
    projectId: 'flash-chat-ea0e6',
    authDomain: 'flash-chat-ea0e6.firebaseapp.com',
    storageBucket: 'flash-chat-ea0e6.appspot.com',
    measurementId: 'G-8X4RQ0RL45',
  );

}